
version: '3.8'

services:

  devs-endava:
    image: openjdk:11
    container_name: java-proyect
    volumes:
      - ./target/${artifact}:/${artifact}
    ports:
      - '80:8080'
    command: ["java","-jar","${artifact}"]
  
  devs-database:
    image: mysql:latest
    container_name: db-proyect
    volumes:
      -"${path-db}:/var/lib/mysql"
    ports:
      -"3306:3306"